name: dermacek
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI and design
  google_fonts: ^6.3.1
  cupertino_icons: ^1.0.8

  # Image and Camera
  image: ^4.5.4
  #image_picker_gallery_camera: ^0.3.0
  image_picker: ^1.2.0
  camera: ^0.11.2

  http: ^1.5.0
  provider: ^6.1.5+1

  # TFlite
  tflite_flutter: ^0.11.0

  # Maps and location
  geolocator: ^14.0.2
  google_maps_flutter: ^2.13.1
  url_launcher: ^6.3.2

  # Data storage
  shared_preferences: ^2.5.3  
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  
  # Visualization
  fl_chart: ^1.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/model/skin_disease_model.tflite
    - assets/model/labels.txt

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400


